# Project: E01A01
# Makefile created by Dev-C++ 5.0.0.4

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 
OBJ      = E01A01.o $(RES)
LINKOBJ  = E01A01.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/lib" -L"C:/Program Files (x86)/Dev-Cpp/lib/gcc" -static-libstdc++ -static-libgcc  
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/include" 
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/include" 
BIN      = E01A01.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before E01A01.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "E01A01.exe" $(LIBS)

E01A01.o: E01A01.cpp
	$(CPP) -c E01A01.cpp -o E01A01.o $(CXXFLAGS)
